### ISSUE TITLE
document using xdg-portal?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [sodiboo/niri-flake#1]
on nixos, using the niri service my `services.flatpak.enable = true;` would error:

```
To use Flatpak you must enable XDG Desktop Portals with xdg.portal.enable.
```

while i see this mentioned in code here and at niri-src, i haven't figured out how to make this work yet.

following the approach i used on hyprland, i tried e.g.:

```nix
    xdg.portal = {
      enable = true;
      wlr.enable = true;
      extraPortals = with pkgs; [
        xdg-desktop-portal-gnome
      ];
    };
```

this appeared not to satisfy the flatpak service yet tho so far.

**Comment by sodiboo** [comment]
https://github.com/sodiboo/niri-flake/commit/7baf65ab448e45b98928b5b03f74c42e89a0ae9a addresses this the way i'd like it to work. if you need an option for any of the new config items, i'd be happy to provide them, but i don't *think* that should be necessary, so i haven't added any for now.
