### ISSUE TITLE
programs.niri.settings.spawn-at-startup usage

### ISSUE THREAD

**Issue by Titaniumtown** [sodiboo/niri-flake#139]
How can I use `programs.niri.settings.spawn-at-startup`? I tried
```nix
programs.niri.settings.spawn-at-startup = [ "waybar"]
```
and
```nix
programs.niri.settings.spawn-at-startup = [ ["waybar"] ]
```
The docs aren't really clear on the usage. Any help would be appreciated, thanks!

**Comment by sodiboo** [comment]
The schema is an array of attrsets with a single key `command` being the arguments passed. You can see some examples in my config here: https://github.com/sodiboo/nix-config/blob/2a511cbb1734dfce30fbafc9d779935fec773648/niri.mod.nix#L164-L170

```nix
{
  programs.niri.settings.spawn-at-startup = [
    { command = [ "waybar" ]; }
  ];
}
```

There are two reasons this isn't just an array of arrays:

1. I thought it looked bad and confusing. It's not immediately obvious to a reader why we are nesting arrays in that case.
2. This way, it's more extensible if niri adds new properties on the spawn-at-startup nodes. It won't require a breaking API change.

**Comment by Titaniumtown** [comment]
Thank you so much @sodiboo
