### ISSUE TITLE
services.xserver.displayManager got renamed over to services.displayManager

### ISSUE THREAD

**Issue by tulilirockz** [sodiboo/niri-flake#148]
As of [this commit](https://github.com/NixOS/nixpkgs/commit/476b8c276e2ae4c98efd1d8d759029e170c5ca98) there was a tree-wide change in nixos-unstable that moves `services.xserver.displayManager` to `services.displayManager`, making it so no NixOS config can be built if niri-flake is enabled now :( 

The affected file is as as of 1fd2e47ed6f0201dbb29e8e308eeffbaaf19e89a https://github.com/sodiboo/niri-flake/blob/1fd2e47ed6f0201dbb29e8e308eeffbaaf19e89a/flake.nix#L410 

By editing this file so it has some check like this, this issue may be fixed. 
```nix
if (system.stateVersion != "24.05") then services.displayManager.sessionPackages = [cfg.package]; 
else services.xserver.displayManager.sessionPackages = [cfg.package]; 
```

Amazing job with this project!

**Comment by tulilirockz** [comment]
Reversing nixpkgs over to a commit before https://github.com/NixOS/nixpkgs/commit/476b8c276e2ae4c98efd1d8d759029e170c5ca98 makes it so this works again! Just a workaround for people that can't use their thing because of this issue right now. (example commit: https://github.com/NixOS/nixpkgs/commit/5598d81e949c37d5b8668182dea1a4418f209ed9)

**Comment by tulilirockz** [comment]
This is just a tracking issue for this PR https://github.com/sodiboo/niri-flake/pull/146, I didnt see that this was here before

**Comment by sodiboo** [comment]
> By editing this file so it has some check like this, this issue may be fixed.
> 
> ```nix
> if (system.stateVersion != "24.05") then services.displayManager.sessionPackages = [cfg.package]; 
> else services.xserver.displayManager.sessionPackages = [cfg.package]; 
> ```

Note that `system.stateVersion` is not the right property here; it is inherently unrelated to the revision of nixpkgs used or what options are exposed. `stateVersion` is all about the versions of packages used, or more specifically, the version of stateful data used. For programs that can't work with older versions of their state (such as some databases), this option prevents them from being corrupted by a nixpkgs upgrade. It is perfectly normal and expected for this to be a value less than `24.05` even on a `24.05` system.

What i've ended up doing instead is to check `system.nixos.release`, which actually corresponds to the NixOS version and (i think) is reliable for detecting the version of the available configuration options.

https://github.com/sodiboo/niri-flake/blob/66a1eae33763465912bc9e086b2942d55659656e/flake.nix#L448-L457

**Comment by sodiboo** [comment]
Update on nixpkgs' side: As of about 40 minutes ago, the relevant PR has now propagated into all applicable channels ([tracker](https://nixpk.gs/pr-tracker.html?pr=303186)), including `nixos-unstable`. The previous version of this flake would now just produce a warning, but otherwise keep working
