### ISSUE TITLE
Screensharing possible

### ISSUE THREAD

**Issue by AlexD97** [sodiboo/niri-flake#2]
Do I have to add some config to enable screensharing? According to niri's README, screensharing should work. But I can't get it working. I saw you've added the gnome xdg-portal but still there is probably something missing in my config.

**Comment by sodiboo** [comment]
I'll be honest, I don't know really. I haven't tried screensharing, so I don't know for sure that it works, and I also don't know why it would or wouldn't work.

I'm a bit busy at the moment and can't spend much time on this in the coming days, but if you or anyone else would like to find out in that time what's missing and submit a PR, I'd be happy to review and merge it.

**Comment by AlexD97** [comment]
I totally understand. If I find a working config, I'll share it.

**Comment by AlexD97** [comment]
Sorry, I had an error in my config. Screen sharing works fine.
