### ISSUE TITLE
How to use this flake

### ISSUE THREAD

**Issue by mastoca** [sodiboo/niri-flake#277]
I'm unable to understand where to start with this flake. I was able to follow https://wiki.hyprland.org/Nix/ 

Is there some explanation of simple clear ways you can add this to a nixos installation so it's available just like the other Compositors?

**Comment by sodiboo** [comment]
You should add this repo to your inputs [(1)](https://github.com/sodiboo/nix-config/blob/5ccd0eea8dd4122aaba9dbe44f9db39731b585f4/flake.nix#L20), then you can add its NixOS module to your configuration [(2)](https://github.com/sodiboo/nix-config/blob/5ccd0eea8dd4122aaba9dbe44f9db39731b585f4/niri.mod.nix#L7). The available options are documented in [`docs.md`](https://github.com/sodiboo/niri-flake/blob/main/docs.md), but most important of which is `programs.niri.enable`, which installs niri.

This repo also provides home-manager modules. If you have home-manager installed as a NixOS module ([see how](https://nix-community.github.io/home-manager/index.xhtml#sec-flakes-nixos-module)), this flake will automatically add the config modules to your user's configuration. Then, you can access `programs.niri.settings` in your home-manager configuration. All of these options are documented in the [`docs.md`](https://github.com/sodiboo/niri-flake/blob/main/docs.md) file. The relevant home-manager modules are also listed there.

If you press this icon in the top right corner of the documentation file, a sidebar shows up that makes it easier to navigate quickly between sections.
![an icon that represents the document outline, which shows headers in a hierarchical fashion](https://github.com/sodiboo/niri-flake/assets/37938646/433a28ed-251d-486a-a3af-d4730ea8c88a)

**Comment by mastoca** [comment]
@sodiboo  thank you for such a swift response. I'm happy to report that I was able to add niri and will start testing it out. Your flake was smooth experience, thank you for your hard work.

for others that want an example this is the base flake.nix for a nixos install using flakes.

```{
  description = "My flakes configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.11";
    home-manager.url = "github:nix-community/home-manager/release-23.11";
    niri.url = "github:sodiboo/niri-flake";
  };

  outputs = { self, nixpkgs, home-manager, niri, ... }@inputs:
    let
      system = "x86_64-linux";
      specialArgs = inputs // { inherit system; };
      shared-modules = [
        niri.nixosModules.niri
        ({pkgs, ...}: {
          nixpkgs.overlays = [niri.overlays.niri];
          programs.niri.package = pkgs.niri-unstable;
          # programs.niri.package = pkgs.niri-stable;
          # programs.niri.package = pkgs.niri-unstable.override {src = niri-working-tree;};
          environment.variables.NIXOS_OZONE_WL = "1";
          environment.systemPackages = with pkgs; [
            wl-clipboard
            wayland-utils
            libsecret
            cage
          ];
        }) 

        home-manager.nixosModules.home-manager
        {
          home-manager = {
            useUserPackages = true;
            extraSpecialArgs = specialArgs;
          };
        }
      ];
    in
    {
    nixosConfigurations = {
        noisy = nixpkgs.lib.nixosSystem {
          system = system;
          specialArgs = specialArgs;
          modules = shared-modules ++ [ ./configuration.nix];
        };
     };
  };
}
```
in configuration.nix I put 
```
          programs.niri.enable = true;
```

**Comment by Munksgaard** [comment]
This doesn't seem to work for me. I get the following error:

```
sudo nixos-rebuild switch --flake .#church
warning: Git tree '/home/munksgaard/src/philnix' is dirty
building the system configuration...
warning: Git tree '/home/munksgaard/src/philnix' is dirty
error:
       … while calling the 'head' builtin
         at /nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source/lib/attrsets.nix:1575:11:
         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'
         at /nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source/lib/modules.nix:816:9:
          815|     in warnDeprecation opt //
          816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          817|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/m68ikm8045fj7ys7qvgr608z9l70hh1k-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `assertions':

       … while evaluating definitions from `/nix/store/xmvivayngmy9w22p83ab3smm9vb49yi6-source/nixos/common.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: The option `home-manager.users.munksgaard.programs.niri.enable' does not exist. Definition values:
       - In `/nix/store/7ps1cm73cvgllqg8mz1x7x3d3cksh12l-source/church/home.nix': true
```

Any clue what could be going wrong? It seems like the home manager module is not being correctly added?

**Comment by sodiboo** [comment]
@Munksgaard 

`programs.niri.enable` is an option that dictates whether to install niri. When using the NixOS module, only functionality to configure niri is added to home-manager, and the installation happens globally. Simply move this option to your NixOS config instead of the home-manager config.

**Comment by alexvorobiev** [comment]
Why are `libsecret` and `cage` needed? I am trying to switch to Niri my VM (VMWare) which uses xmonad at the moment. Niri gets installed but after logging in (gbm) I am only seeing black screen with (working) mouse cursor.
