### ISSUE TITLE
Desktop Session

### ISSUE THREAD

**Issue by rawkode** [sodiboo/niri-flake#287]
I've got the flake working and I can launch niri manually, but I was wondering if there's a magic trick to get niri as an option with gdm or sddm?

**Comment by rawkode** [comment]
Nevermind. Session wasn't added via home-manager module, but works great when used as nixos module.

**Comment by sodiboo** [comment]
As far as i'm aware, it's not possible to add from the home module. I guess this is because the greeter doesn't run as your user, so it can't read your own user's home directory. It can only see system-wide files, and as such the sessions is can autodetect must be system-wide ones.
