### ISSUE TITLE
update to 0.1.0

### ISSUE THREAD

**Issue by KiaraGrouwstra** [sodiboo/niri-flake#3]
it looks like niri [had a release again](https://github.com/YaLTeR/niri/releases/tag/v0.1.0) 🥳

**Comment by sodiboo** [comment]
This flake now defaults to stable niri. https://github.com/sodiboo/niri-flake/commit/ddf9fac0c3cb86a2112507ca22bbed4abefda4ee.
 
 The README is also updated to reflect this https://github.com/sodiboo/niri-flake/commit/bc35d4d49f225eb581e3f972d9bd21ab33be508d
