### ISSUE TITLE
Nixpkgs 23.11 compatibility

### ISSUE THREAD

**Issue by Kha** [sodiboo/niri-flake#32]
Using niri-flake as a NixOS modulo seems to use the NixOS nixpkgs, which doesn't know about `--replace-fail` yet on 23.11:
```
error: builder for '/nix/store/kpcz07qm41dxi5x7lzkxmgmy59bxd5ds-rust_niri-config-0.1.2.drv' failed with exit code 1;
       last 6 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/mmczsxgmcidlpksshfw3gky7yw1rpwny-source/niri-config
       > source root is niri-config
       > Running phase: patchPhase
       > substituteStream(): ERROR: Invalid command line argument: --replace-fail
       > /nix/store/10i1kjjq5szjn1gp6418x8bc1hswqc90-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/kpcz07qm41dxi5x7lzkxmgmy59bxd5ds-rust_niri-config-0.1.2.drv'.
```

**Comment by Kha** [comment]
It does, thanks!

I didn't think running stable was particularly objectionable :) . From the feeling I got from discourse.nixos, quite a few people do it, though perhaps not the majority. For me it's mainly about less frequent updates in both download size and chance for breakage, e.g. not coming back to my PC recompiling libreoffice because it failed on hydra.

**Comment by sodiboo** [comment]
I've added nixpkgs stable to the CI workflow that caches builds. If you install the binary cache (done automatically with NixOS module), you will no longer need to build it locally: https://github.com/sodiboo/niri-flake/actions/runs/8214390531/job/22466834264#step:6:1
