### ISSUE TITLE
cannot screen share separate windows

### ISSUE THREAD

**Issue by KiaraGrouwstra** [sodiboo/niri-flake#344]
i'm trying to follow [the niri v0.1.7 instructions](https://github.com/YaLTeR/niri/releases/tag/v0.1.7), but hadn't gotten window sharing to work yet (in either OBS Studio or Jitsi).

![image](https://github.com/sodiboo/niri-flake/assets/3059397/9c970569-bda8-4436-b949-56fa885c7981)

i seem able to reproduce this issue under what seems like [no funny overrides](https://codeberg.org/kiara/cfg/compare/main...reproduce-niri-window-sharing-issue)

was this already working better for you?

**Comment by KiaraGrouwstra** [comment]
just remembered i should prob reboot niri first at least. looks like there's other issues on reboot still tho, so i should prob first look into those.

**Comment by sodiboo** [comment]
> was this already working better for you?

yeah, it works for me.
