### ISSUE TITLE
error "The option `hardware.graphics` does not exist" on stable `nixosSystem` with unstable `pkgs`

### ISSUE THREAD

**Issue by KiaraGrouwstra** [sodiboo/niri-flake#351]
i'm currently running nixpkgs versions separated between my `nixosSystem` call vs my packages (no minimum repro yet), which i hoped would help keep my system stable while giving the flexibility of trying new stuff.
`niri-flake` now uses [`config.system.nixos.release`](https://github.com/sodiboo/niri-flake/commit/38186d3da0497d14404980289c5515d828b78edc#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R463) to determine whether it can use `graphics.enable`, which seemed to under my setup fail.
i'm not sure this is worth investigating as we're all bound to update system, but i figured i'd at least file this here in case others also run into this (and we'd get closer to a repro).

**Comment by sodiboo** [comment]
huh? so you're calling `nixosSystem` with modules from 24.05, then? shouldn't `config.system.nixos.release` be 24.05 in that case? what is it on your system? how did this happen

**Comment by KiaraGrouwstra** [comment]
i wanted to use AMD gpu acceleration, which takes ages to build while caching for it seemed flaky earlier.
i'd wanted to solve crap like that by just keeping my system on stable then, while basically keeping everything else in home-manager (which would just use unstable nixpkgs). 😅
at this point i also just updated tho. 😅
