### ISSUE TITLE
Please add support for `focus-follows-mouse max-scroll-amount="N%"`

### ISSUE THREAD

**Issue by algernon** [sodiboo/niri-flake#379]
Recentish niri unstable has a new (optional) parameter for `focus-follows-mouse`: `max-scroll-amount="N%"`. It would be amazing if this flake supported that.

I tried adding it myself, but sadly my brain is in a "nope, we're not writing any Nix now" mood.

**Comment by sodiboo** [comment]
This has been implemented now :3

It's done as a breaking change because i didn't feel like writing an automatic migration layer right now.

The three users i could find who are affected on github and present in the Matrix channel have been notified via Matrix.
