### ISSUE TITLE
Possible to use niri.homeModules.config w/o using home-manager as a module?

### ISSUE THREAD

**Issue by bndlfm** [sodiboo/niri-flake#456]
I tend not to use home-manager as a nixos module to cut down on rebuild times.

I've tried importing it into my flake as a module directly into homeConfigurations but it doesn't seem to work.

**Comment by sodiboo** [comment]
`niri.homeModules.config` should work fine if you import just that one. This is a supported/intended way to use this flake. What exactly isn't working? Do you have a configuration available anywhere? Are you getting any errors? What do you expect the module to do which it doesn't?

**Comment by bndlfm** [comment]
I'm still somewhat new to the nix ecosystem so I'm probably just missing something. I've tried `niri.homeModules.config (import path/to/niriconfig.nix {inherit niri;})` and just placing the config in my flake directly but either way I get an error:

`       error: The option `programs.niri.enable' does not exist. Definition values:
       - In `<unknown-file>': true`

[My flake.nix](https://github.com/bndlfm/dot.nix/blob/main/flake.nix)

**Comment by sodiboo** [comment]
`programs.niri.enable` is not provided for `niri.homeModules.config` module. This option enables various services used to run niri - the config module *only* serves to generate `~/.config/niri/config.kdl` from a Nix-based configuration. It doesn't make sense to "enable" or "disable" this behaviour; you can prevent it by just setting the config to null. You can also see [the full home-manager side of its implementation here](https://github.com/sodiboo/niri-flake/blob/dcd1772fb763ba9cfa179a378b9e08f4f2d4d789/flake.nix#L484-L505). (this is like 20 lines). The config module is also documented such that [you can search in this file for options](https://github.com/sodiboo/niri-flake/blob/main/docs.md#homemodulesconfig).
