### ISSUE TITLE
xwayland-satellite not installed?

### ISSUE THREAD

**Issue by zero64801** [sodiboo/niri-flake#463]
I added the git to my flake and to nixos configuration then programs.niri.enabled = true which works perfectly but xwayland-satellite isn't installed,did I miss something or is this a issue, I don't have xwayland installed but even installing it wont change anything.

**Comment by sodiboo** [comment]
The module only enables niri, not xwayland-satellite. If you add `nixpkgs.overlays = [niri.overlays.niri];`, then this flake will provide you a more up-to-date `pkgs.xwayland-satellite` than in nixpkgs, but it does nothing else at the moment. You must install and enable `xwayland-satellite` manually.
