### ISSUE TITLE
fullscreen freezing

### ISSUE THREAD

**Issue by zero64801** [sodiboo/niri-flake#465]
I tested only with steam but maybe happens with other apps aswell, when fullscreen steam games ( maybe happen with other apps aswell, didn't test ) the screen will freeze/lag without any sign of coming back I can switch to another tty even though it takes a while to do so. I looked through other closed issues which mentioned something equal/similliar which was marked as solved, the thing that fixed it for me now was disabling direct scanout like mentioned before. ( I'm running in a nvidia gpu/proprietary driver 550.78 )

**Comment by sodiboo** [comment]
I'm not sure what the other closed issue you're referring to is, assuming it's in this repo. But this issue doesn't seem to be related to this flake. [Did you mean to open it here?](https://github.com/YaLTeR/niri/issues)

**Comment by zero64801** [comment]
> I'm not sure what the other closed issue you're referring to is, assuming it's in this repo. But this issue doesn't seem to be related to this flake. [Did you mean to open it here?](https://github.com/YaLTeR/niri/issues)

Yes, I didn't realize it ill post it there
