### ISSUE TITLE
`programs.niri.settings` does not exist

### ISSUE THREAD

**Issue by blank2121** [sodiboo/niri-flake#563]
I have tried multiple things with my goal being to have a folder with my Wayland compositors and I want to configure niri in that. AKA having some `niri.nix`. I have the `niri.nixosModules.niri` in my nixos flake and I have added the niri overlay as well. I additionally tried adding this directly to the modules in the flake as I saw it in another issue.
```
            ({pkgs, ...}: 
            {
                nixpkgs.overlays = [niri.overlays.niri];
                programs.niri.package = pkgs.niri-unstable;
                # programs.niri.package = pkgs.niri-stable;
                # programs.niri.package = pkgs.niri-unstable.override {src = niri-working-tree;};
                programs.niri.settings = {
                    outputs."eDP-1".scale = 2.0;
                };
                environment.variables.NIXOS_OZONE_WL = "1";
                environment.systemPackages = with pkgs; [
                    wl-clipboard
                    wayland-utils
                    libsecret
                    cage
                ];
            })
```
but that didn't work either. 

Here is my flake.nix file and the niri.nix file (files are in order)
```
{
  description = "My NixOS Home :)";

  inputs = {
    nixpkgs = {
      url = "github:nixos/nixpkgs/nixos-unstable";
    };
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-flatpak.url = "github:gmodena/nix-flatpak";
    nixos-hardware.url = "github:Nixos/nixos-hardware/master";
    nixvim.url = "github:blank2121/nixvim";
    stylix.url = "github:danth/stylix";
    # lix-module = {
    #   url = "https://git.lix.systems/lix-project/nixos-module/archive/2.91.0.tar.gz";
    #   inputs.nixpkgs.follows = "nixpkgs";
    # };
    niri.url = "github:sodiboo/niri-flake";
  };

  outputs = { self, home-manager, niri, nix-flatpak, 
  nixos-hardware, nixpkgs, stylix, ... }@inputs:
    let 
      system = "x86_64-linux";
      pkgs = import nixpkgs { 
        inherit system;
        config.allowUnfree = true;
        overlays = [
          niri.overlays.niri
        ];
      };
    in {
      nixosConfigurations = {
        main = nixpkgs.lib.nixosSystem {
          inherit pkgs;
          specialArgs = { inherit inputs; };
          modules = [
            ./hosts/main/configuration.nix
            home-manager.nixosModules.default
            nixos-hardware.nixosModules.asus-zephyrus-ga402x-amdgpu
            niri.nixosModules.niri
            stylix.nixosModules.stylix
            # lix-module.nixosModules.default
          ];
        };
      };
    };
}
```

niri.nix

```
{pkgs, inputs, ...}: 
{
    # nixpkgs.overlays = [inputs.niri.overlays.niri];
    programs.niri.package = pkgs.niri-unstable;
    # programs.niri.package = pkgs.niri-stable;
    # programs.niri.package = pkgs.niri-unstable.override {src = niri-working-tree;};
    programs.niri.settings = {
        outputs."eDP-1".scale = 2.0;
    };
    environment.variables.NIXOS_OZONE_WL = "1";
    environment.systemPackages = with pkgs; [
        wl-clipboard
        wayland-utils
        libsecret
        cage
    ];
}
```

and yes, I have tried importing and adding the overlay directly in the file. Who ever has done something similar to what I am going for, please be my savior as I love the idea behind this project.

**Comment by sodiboo** [comment]
does it work if you do that?

```diff
-    programs.niri.settings = {
+    home-manager.users.winston.programs.niri.settings = {
         outputs."eDP-1".scale = 2.0;
     };
```

**Comment by blank2121** [comment]
damn it.... Thank you! this works! I just wished that the set-up process was a bit better spelled out for users. If I can, I would love to document a "setup" for this just because I think other people would also benefit from this. Thanks for resolving my issue!

**Comment by sodiboo** [comment]
> This `with config.lib.niri.actions;` is giving me some issues where it says attribute niri is missing

That's for the same reason that `programs.niri.settings` is missing. Both of these things are currently only available in the home-manager module, and `config` in that expression is supposed to refer to your home-manager config and not your NixOS config. Since you're using home-manager within NixOS and defining home manager options from NixOS modules, you can access it like `with config.home-manager.users.winston.lib.niri.actions;`

> can you [...] tell me how I bind keys without using `config.lib.niri.actions`

[the documentation](https://github.com/sodiboo/niri-flake/blob/main/docs.md#programsnirisettingsbindsnameaction) explains how action values are shaped, *before* then showing you the convenience attrset that allows you to define them in a more close-to-the-actual-config DSL. In short, `.action = ACTION_NAME arg1 arg2 arg3;` becomes `.action.ACTION_NAME = [ arg1 arg2 arg3 ];` (and you can omit the brackets if there is exactly one arg)

**Comment by sodiboo** [comment]
Did you get it all working? Were all your questions answered sufficiently? If so, you can close the issue.

**Comment by blank2121** [comment]
![screenshot-2024-10-27](https://github.com/user-attachments/assets/04972cd8-143f-4b5f-a564-b65306296895)
its all good now! thank you and now my setup is looking great!
