### ISSUE TITLE
niri update breaks nix build

### ISSUE THREAD

**Issue by KiaraGrouwstra** [sodiboo/niri-flake#6]
https://github.com/YaLTeR/niri/issues/181

**Comment by sodiboo** [comment]
Does it really? It seems to work fine on my system still, without any changes whatsoever.

`crate2nix` doesn't "blindly" run cargo commands; instead it parses the `Cargo.toml`, and builds only what i ask. In the case of this flake, i'm only building the `niri` crate and all of its dependencies; of which `niri-visual-tests` is not one. New dependencies can break my builds (`niri-config` uses some relative path that doesn't exist in the build environment, so i have to override it with the correct absolute path, for example), but new crates that `niri` does not depend on, generally, cannot.

The `niri-visual-tests` crate's derivation is generated just fine, though. it just isn't built, and i don't plan on supporting it.

This update does not break my flake.
